##############################################################################
## Deprovision cicd
##############################################################################

- name: create build project
  openshift_v1_project:
    name: "{{ build_namespace }}"
    state: absent

- name: create test project
  openshift_v1_project:
    name: "{{ test_namespace }}"
    state: absent

- name: create prod project
  openshift_v1_project:
    name: "{{ prod_namespace }}"
    state: absent
